### ISSUE TITLE
Tested with docx but dosen't work

### ISSUE THREAD

**Issue by v3ss0n** [igumnoff/shiva#122]
I tried docx but it saids 

```
thread 'main' panicked at lib/src/docx.rs:285:29:
not implemented: Should implement
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by evgenyigumnov** [comment]
Could you provide your code? Please

**Comment by evgenyigumnov** [comment]
And test data the same, please.

**Comment by v3ss0n** [comment]
I just rand it from cli. 

[DOJ_2016.docx](https://github.com/user-attachments/files/17308416/DOJ_2016.docx)

**Comment by evgenyigumnov** [comment]
Could you provide your command line execution example?

**Comment by v3ss0n** [comment]
thank you. 

```
./shiva DOJ_2016.docx out.markdown                                                                                                                                                                
./shiva DOJ_2016.docx out.html  
````

**Comment by evgenyigumnov** [comment]
Ok, thanks. I will check and try to fix during next couple days. I am on vocation now.

**Comment by evgenyigumnov** [comment]
Fixed

**Comment by v3ss0n** [comment]
Thank you very much , I am trying a few different libs for mulit-docment extraction. So Far only Shiva could be better alternative to Tika - which don't have any format and table extraction  , which are important for LLMs and DL.

**Comment by evgenyigumnov** [comment]
Thanks! Just say it to your friend in social network! It will help us!

**Comment by v3ss0n** [comment]
Yes shared with my team.
Do you have plan to support Doc ?

**Comment by evgenyigumnov** [comment]
Yeap.
