### ISSUE TITLE
Allow standard markdown extension in `bin`, ie `.md` as well as `.markdown`

### ISSUE THREAD

**Issue by jmetz** [igumnoff/shiva#124]
At the moment the _`shiva` binary_ complains if I try e.g. 

```
shiva sample.md sample.pdf
```

and instead requires renaming to `.markdown`. As `.md` is one of the standard markdown file extensions (possibly more common than `.markdown`?), this is seems illogical.

**Comment by evgenyigumnov** [comment]
yeap. we need add alias "md" for "markdown"

are you redy to do it?
