### ISSUE TITLE
RTF parser

### ISSUE THREAD

**Issue by evgenyigumnov** [igumnoff/shiva#41]
1. Implement "RTF parser" (parse function)
```
pub trait TransformerTrait {
    fn parse(document: &Bytes, images: &HashMap<String, Bytes>) -> anyhow::Result<Document>;
    fn generate(document: &Document) -> anyhow::Result<(Bytes, HashMap<String, Bytes>)>;
}

```
2. Units test requered for this new feature

recommended crates:

```rtf-parser = "0.3.0"```

**Comment by Christiantyemele** [comment]
hello @evgenyigumnov I have gone through the project and I found out that every file format implemented its own parse function of the TransformerTrait. so I want to what is expected from me here , a default implementation ?.

**Comment by evgenyigumnov** [comment]
I do not understand exactly what is "default implementation".

You should create mod rtf.rs and implement only "fn parse(document: &Bytes, images: &HashMap<String, Bytes>) -> anyhow::Result<Document>;"

For generate function just use "todo!() "

This mod should work with rtf document format and support this functional points:

Header | Paragraph | List | Table | Image | Hyperlink | PageHeader | PageFooter
