### ISSUE TITLE
docx parser skips content in separate runs

### ISSUE THREAD

**Issue by magikmw** [igumnoff/shiva#94]
I'm having issues with the docx parser skipping over content when it's placed in the docx file in separate runs, but appears in the same line or paragraph.

In following example I'm looking for 
Part of docx I'm testing looks like this in the document.xml:

```xml
        <w:p>
            <w:pPr>
                <w:pStyle w:val="Normal" />
                <w:jc w:val="right" />
                <w:rPr>
                    <w:szCs w:val="22" />
                </w:rPr>
            </w:pPr>
            <w:r>
                <w:rPr>
                    <w:szCs w:val="22" />
                </w:rPr>
                <w:t xml:space="preserve">Warszawa, dnia </w:t>
            </w:r>
            <w:r>
                <w:rPr>
                    <w:b />
                    <w:bCs />
                    <w:szCs w:val="22" />
                    <w:shd w:fill="FFFF00" w:val="clear" />
                </w:rPr>
                <w:t>{{</w:t>
            </w:r>
            <w:r>
                <w:rPr>
                    <w:b />
                    <w:bCs />
                    <w:szCs w:val="22" />
                    <w:shd w:fill="FFFF00" w:val="clear" />
                </w:rPr>
                <w:t>DATA</w:t>
            </w:r>
            <w:r>
                <w:rPr>
                    <w:b />
                    <w:bCs />
                    <w:szCs w:val="22" />
                    <w:shd w:fill="FFFF00" w:val="clear" />
                </w:rPr>
                <w:t>}}</w:t>
            </w:r>
            <w:r>
                <w:rPr>
                    <w:szCs w:val="22" />
                </w:rPr>
                <w:t xml:space="preserve"> r. </w:t>
            </w:r>
        </w:p>
```

And output of document.elements looks like this:

```
Document { elements: [Text { text: "", size: 16 }, Text { text: "Warszawa, dnia ", size: 16} [... array elements continue]
```

This is just the first instance of the text being skipped over by the parser, there's a few more in the same file.
I can't provide the file itself, as it's proprietary, but if needed I'd try to reproduce on a fresh file.

**Comment by evgenyigumnov** [comment]
Hello, thank you!
We will try fix it soon.

**Comment by Longlom** [comment]
@magikmw 
Hello 
Can you provide the expected result and actual result ?

**Comment by magikmw** [comment]
Sure - the document I mentioned in description contains a line like this:
`Warszawa, dnia {{DATA}}`

However, parsing the docx with shiva outputs just:
`Warszawa, dnia`

As you can see in the xml from the discription, the line contained in a single paragraph (`<w:p>` tag), but split into 4 runs (`<w:r>` tags):
`Warszawa, dnia`
`{{`
`DATA`
`}}`

Somehow, shiva skips over run tags 2-4 (index 1).

The same document has several instances of this.

As far as I understand, MS Word has some unknowable internal logic of what goes into which run, and a paragraph can has several, as in this example.

For now I'm pivoting to using a package `python-docx` [doc link](https://python-docx.readthedocs.io/en/latest/) as it seems to parse docx correctly (for now).

**Comment by Longlom** [comment]
https://github.com/igumnoff/shiva/pull/103

fixing in
